<a href="https://colab.research.google.com/github/kesavraov-2005/Cleaned-Airline-Database-/blob/main/pandas_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1.	Import the Pandas library and load the dataset
import pandas as pd

In [ ]:

a=pd.read_csv("/content/uncleaned_airline_dataset_20_columns.csv")
a

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.0,NaN,Non-Veg,30kg,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.0,Non-Refundable,NONE,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,NaN,Non-Refundable,Non-Veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.0,NaN,NaN,30kg,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.0,NaN,NONE,unknown,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2.0,Non-Refundable,NaN,25,NaN,T3,0,C101
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,1.0,NON REFUNDABLE,Non-Veg,15,Checked-In,T1,15,C104
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,NaN,NON REFUNDABLE,NONE,NaN,NaN,NaN,unknown,C103
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,4.0,Non-Refundable,Non-Veg,15,NaN,terminal-2,5,C104
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2.0,NON REFUNDABLE,veg,25,NaN,NaN,unknown,C104

In [ ]:
#2. display the first 10 rows of the dataset
a.head(10)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.0,NaN,Non-Veg,30kg,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.0,Non-Refundable,NONE,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,NaN,Non-Refundable,Non-Veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.0,NaN,NaN,30kg,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.0,NaN,NONE,unknown,checked-in,T3,NaN,C101
5,5,Vistara,UK-945,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.33,1,5955,4.0,refundable,NaN,15,Checked-In,T2,0,C103
6,6,Vistara,UK-927,Delhi,Morning,zero,Morning,Mumbai,Economy,2.08,1,6060,4.0,refundable,veg,30kg,Not Checked,T2,5,C101
7,7,Vistara,UK-951,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.17,1,6060,4.0,NON REFUNDABLE,NONE,15,Not Checked,T2,NaN,NaN
8,8,GO_FIRST,G8-334,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5954,2.0,refundable,Veg,unknown,checked-in,T1,15,C104
9,9,GO_FIRST,G8-336,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5954,4.0,NON REFUNDABLE,Non-Veg,25,Not Checked,T1,unknown,C104

In [ ]:
#3.	Display the last 10 rows of the dataset.
a.tail(10)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
300143,300143,Air_India,AI-440,Chennai,Early_Morning,one,Night,Hyderabad,Business,17.42,49,51345,NaN,NaN,NONE,25,Checked-In,T1,30,NaN
300144,300144,Air_India,AI-539,Chennai,Evening,one,Morning,Hyderabad,Business,18.92,49,51345,5.0,Non-Refundable,Veg,unknown,Not Checked,Terminal 1,unknown,C105
300145,300145,Air_India,AI-430,Chennai,Morning,one,Morning,Hyderabad,Business,23.08,49,51345,4.0,NON REFUNDABLE,veg,20,checked-in,Terminal 1,60,C105
300146,300146,Air_India,AI-440,Chennai,Early_Morning,one,Morning,Hyderabad,Business,26.83,49,51345,4.0,NON REFUNDABLE,veg,30kg,checked-in,T3,10,NaN
300147,300147,Air_India,AI-569,Chennai,Early_Morning,one,Night,Hyderabad,Business,17.25,49,68739,3.0,Refundable,veg,25,Checked-In,terminal-2,10,C104
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2.0,Non-Refundable,NaN,25,NaN,T3,0,C101
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,1.0,NON REFUNDABLE,Non-Veg,15,Checked-In,T1,15,C104
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,NaN,NON REFUNDABLE,NONE,NaN,NaN,NaN,unknown,C103
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,4.0,Non-Refundable,Non-Veg,15,NaN,terminal-2,5,C104
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2.0,NON REFUNDABLE,veg,25,NaN,NaN,unknown,C104

In [ ]:
#4.	Find the total number of rows and columns in the dataset
a.shape

(300153, 20)

In [ ]:
#5.	Display the list of all column names
a.columns

Index(['index', 'airline', 'flight', 'source_city', 'departure_time', 'stops',
       'arrival_time', 'destination_city', 'class', 'duration', 'days_left',
       'price', 'Passenger_Rating', 'Ticket_Type', 'Meal_Option', 'Baggage_kg',
       'Checkin_Status', 'Airport_Terminal', 'Delay_Minutes', 'Customer_ID'],
      dtype='object')

In [ ]:
#6.	Display the data types of all columns.
a.dtypes

index                 int64
airline              object
flight               object
source_city          object
departure_time       object
stops                object
arrival_time         object
destination_city     object
class                object
duration            float64
days_left             int64
price                 int64
Passenger_Rating    float64
Ticket_Type          object
Meal_Option          object
Baggage_kg           object
Checkin_Status       object
Airport_Terminal     object
Delay_Minutes        object
Customer_ID          object
dtype: object

In [ ]:
#7.	Display basic statistical summary of the dataset.
a.describe()

,index,duration,days_left,price,Passenger_Rating
count,300153.000000,300153.000000,300153.000000,300153.000000,224988.000000
mean,150076.000000,12.221021,26.004751,20889.660523,3.172458
std,86646.852011,7.191997,13.561004,22697.767366,1.342857
min,0.000000,0.830000,1.000000,1105.000000,1.000000
25%,75038.000000,6.830000,15.000000,4783.000000,2.000000
50%,150076.000000,11.250000,26.000000,7425.000000,4.000000
75%,225114.000000,16.170000,38.000000,42521.000000,4.000000
max,300152.000000,49.830000,49.000000,123071.000000,5.000000

In [ ]:
#8.	Identify which columns contain missing values.
a.columns.isnull()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [ ]:
#9.	Count the number of missing values in each column
a.isnull().sum()

index               0
airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
Passenger_Rating    0
Ticket_Type         0
Meal_Option         0
Baggage_kg          0
Checkin_Status      0
Airport_Terminal    0
Delay_Minutes       0
Customer_ID         0
dtype: int64

In [ ]:
#9.	Count the number of missing values in each column
a.nunique()

index               300153
airline                  6
flight                1561
source_city              6
departure_time           6
stops                    3
arrival_time             6
destination_city         6
class                    2
duration               476
days_left               49
price                12157
Passenger_Rating         5
Ticket_Type              4
Meal_Option              4
Baggage_kg               5
Checkin_Status           4
Airport_Terminal         5
Delay_Minutes            7
Customer_ID              5
dtype: int64

In [ ]:
#11.	Replace missing values in Passenger_Rating with the mean value.
b = a["Passenger_Rating"].mean()
(a["Passenger_Rating"].fillna((b), inplace=True))
a

/tmp/ipykernel_4999/902110171.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  (a["Passenger_Rating"].fillna((b), inplace=True))

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.000000,NaN,Non-Veg,30kg,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.000000,Non-Refundable,NONE,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,3.172458,Non-Refundable,Non-Veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.000000,NaN,NaN,30kg,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.000000,NaN,NONE,unknown,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2.000000,Non-Refundable,NaN,25,NaN,T3,0,C101
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,1.000000,NON REFUNDABLE,Non-Veg,15,Checked-In,T1,15,C104
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,3.172458,NON REFUNDABLE,NONE,NaN,NaN,NaN,unknown,C103
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,4.000000,Non-Refundable,Non-Veg,15,NaN,terminal-2,5,C104
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2.000000,NON REFUNDABLE,veg,25,NaN,NaN,unknown,C104

In [ ]:
#12.	Replace missing values in Meal_Option with "Unknown".
(a["Meal_Option"].fillna(("Unknown"),inplace=True))
a

/tmp/ipykernel_4999/688848865.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  (a["Meal_Option"].fillna(("Unknown"),inplace=True))

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.000000,NaN,Non-Veg,30kg,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.000000,Non-Refundable,NONE,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,3.172458,Non-Refundable,Non-Veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.000000,NaN,Unknown,30kg,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.000000,NaN,NONE,unknown,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2.000000,Non-Refundable,Unknown,25,NaN,T3,0,C101
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,1.000000,NON REFUNDABLE,Non-Veg,15,Checked-In,T1,15,C104
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,3.172458,NON REFUNDABLE,NONE,NaN,NaN,NaN,unknown,C103
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,4.000000,Non-Refundable,Non-Veg,15,NaN,terminal-2,5,C104
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2.000000,NON REFUNDABLE,veg,25,NaN,NaN,unknown,C104

In [ ]:
#13.	Replace missing values in Baggage_kg with the median value.
import numpy as np

In [ ]:
a["Baggage_kg"].replace({"30kg":30},inplace=True)

/tmp/ipykernel_4999/1966805566.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  a["Baggage_kg"].replace({"30kg":30},inplace=True)

In [ ]:
a["Baggage_kg"]=a["Baggage_kg"].replace("unknown",np.nan)

In [ ]:
a["Baggage_kg"].fillna(a["Baggage_kg"].median())

0           30
1         20.0
2           25
3           30
4         20.0
          ...
300148      25
300149      15
300150    20.0
300151      15
300152      25
Name: Baggage_kg, Length: 300153, dtype: object

In [ ]:
#14.	Remove rows where Customer_ID is missing.
a.dropna(subset=["Customer_ID"],inplace=True)

In [ ]:
#15.	Verify that missing values are handled.
a.isnull().sum()

index               0
airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
Passenger_Rating    0
Ticket_Type         0
Meal_Option         0
Baggage_kg          0
Checkin_Status      0
Airport_Terminal    0
Delay_Minutes       0
Customer_ID         0
dtype: int64

In [ ]:
#16.	Remove leading and trailing spaces from all string columns.
a.columns=a.columns.str.strip()
a

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.000000,NaN,Non-Veg,30,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.000000,Non-Refundable,NONE,NaN,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,3.172458,Non-Refundable,Non-Veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.000000,NaN,Unknown,30,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.000000,NaN,NONE,NaN,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2.000000,Non-Refundable,Unknown,25,NaN,T3,0,C101
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,1.000000,NON REFUNDABLE,Non-Veg,15,Checked-In,T1,15,C104
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,3.172458,NON REFUNDABLE,NONE,NaN,NaN,NaN,unknown,C103
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,4.000000,Non-Refundable,Non-Veg,15,NaN,terminal-2,5,C104
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2.000000,NON REFUNDABLE,veg,25,NaN,NaN,unknown,C104

In [ ]:
#17.	Convert Meal_Option values to lowercase.
e=a["Meal_Option"]=a["Meal_Option"].str.upper()
e=inplace = True
a

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.000000,NaN,NON-VEG,30,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.000000,Non-Refundable,NONE,NaN,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,3.172458,Non-Refundable,NON-VEG,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.000000,NaN,UNKNOWN,30,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.000000,NaN,NONE,NaN,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2.000000,Non-Refundable,UNKNOWN,25,NaN,T3,0,C101
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,1.000000,NON REFUNDABLE,NON-VEG,15,Checked-In,T1,15,C104
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,3.172458,NON REFUNDABLE,NONE,NaN,NaN,NaN,unknown,C103
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,4.000000,Non-Refundable,NON-VEG,15,NaN,terminal-2,5,C104
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2.000000,NON REFUNDABLE,VEG,25,NaN,NaN,unknown,C104

In [ ]:
#18.	Convert Ticket_Type values to proper format (Refundable / Non-Refundable).
a["Ticket_Type"].unique()

array([nan, 'Non-Refundable', ' refundable ', 'NON REFUNDABLE',
       'Refundable'], dtype=object)

In [ ]:
a["Ticket_Type"].replace({"refundable":"Refundable","NON REFUNDABLE":"Non-Refundable"," refundable ":"Refundable"})
a["Ticket_Type"]

0                    NaN
1         Non-Refundable
2         Non-Refundable
3                    NaN
4                    NaN
               ...
300148    Non-Refundable
300149    NON REFUNDABLE
300150    NON REFUNDABLE
300151    Non-Refundable
300152    NON REFUNDABLE
Name: Ticket_Type, Length: 250526, dtype: object

In [ ]:
#19.	Standardize Checkin_Status values.
a["Checkin_Status"].unique()

array(['Not Checked', 'checked-in', '  checked ', nan, 'Checked-In'],
      dtype=object)

In [ ]:
a["Checkin_Status"].replace(({"Not Checked":"Not-Checked","checked-in":"Checked","checked":"Checked","nan":"Not-Checked","Checked-In":"Checked"}),inplace=True)
a["Checkin_Status"]

0         Not-Checked
1             Checked
2            checked
3                 NaN
4             Checked
             ...
300148            NaN
300149        Checked
300150            NaN
300151            NaN
300152            NaN
Name: Checkin_Status, Length: 250526, dtype: object

In [ ]:
#20.	Standardize Airport_Terminal values to T1, T2, T3 format.
a["Airport_Terminal"].unique()

array(['T2', nan, 'terminal-2', 'T3', 'T1', 'Terminal 1'], dtype=object)

In [ ]:
a["Airport_Terminal"].replace(({"terminal-2":"T2","Terminal 1":"T1"}),inplace=True)
a["Airport_Terminal"]

/tmp/ipykernel_4999/2830709963.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  a["Airport_Terminal"].replace(({"terminal-2":"T2","Terminal 1":"T1"}),inplace=True)

0          T2
1         NaN
2          T2
3          T2
4          T3
         ...
300148     T3
300149     T1
300150    NaN
300151     T2
300152    NaN
Name: Airport_Terminal, Length: 250526, dtype: object

In [ ]:
#21.	Convert Passenger_Rating column to numeric datatype
h=a["Passenger_Rating"]=a["Passenger_Rating"].astype(int)
h=inplace=True
a["Passenger_Rating"].dtype

dtype('int64')

In [ ]:
#22.	Convert Baggage_kg values by removing "kg" text.
a["Baggage_kg"].replace(({"30kg":"30"}),inplace=True)
a["Baggage_kg"]

/tmp/ipykernel_4999/2326592008.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  a["Baggage_kg"].replace(({"30kg":"30"}),inplace=True)

0          30
1         NaN
2          25
3          30
4         NaN
         ...
300148     25
300149     15
300150    NaN
300151     15
300152     25
Name: Baggage_kg, Length: 250526, dtype: object

In [ ]:
#23.	Convert Delay_Minutes column into integer datatype.
a["Delay_Minutes"].unique()

array(['30', '10', 'unknown', nan, '0', '5', '15', '60'], dtype=object)

In [ ]:
a["Delay_Minutes"].replace({"30":30,"10":10,"0":0,"5":5,"15":15,"60":60},inplace=True)

/tmp/ipykernel_4999/856064165.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  a["Delay_Minutes"].replace({"30":30,"10":10,"0":0,"5":5,"15":15,"60":60},inplace=True)

In [ ]:
a["Delay_Minutes"].replace("unknown",np.nan,inplace=True)

/tmp/ipykernel_4999/3137656601.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  a["Delay_Minutes"].replace("unknown",np.nan,inplace=True)

In [ ]:
a["Delay_Minutes"].fillna(a["Delay_Minutes"].median(),inplace=True)

In [ ]:
a["Delay_Minutes"].astype(int)

0         30
1         10
2         10
3         10
4         10
          ..
300148     0
300149    15
300150    10
300151     5
300152    10
Name: Delay_Minutes, Length: 250526, dtype: int64

In [ ]:
#25.	Verify the updated data types.
a["Passenger_Rating"].dtype

dtype('int64')

In [ ]:
a["Delay_Minutes"].dtype

dtype('float64')

In [ ]:
#26.	Check whether duplicate rows exist in the dataset.
a.duplicated().any()

np.False_

In [ ]:
#27.	Count the number of duplicate rows.
a.duplicated().sum()

np.int64(0)

In [ ]:
#28.	Remove duplicate rows from the dataset.
a.drop_duplicates(inplace=True)

In [ ]:
a.columns

Index(['index', 'airline', 'flight', 'source_city', 'departure_time', 'stops',
       'arrival_time', 'destination_city', 'class', 'duration', 'days_left',
       'price', 'Passenger_Rating', 'Ticket_Type', 'Meal_Option', 'Baggage_kg',
       'Checkin_Status', 'Airport_Terminal', 'Delay_Minutes', 'Customer_ID'],
      dtype='object')

In [ ]:
#29.	Find the total number of flights in the dataset.
a["flight"].count()

np.int64(250526)

In [ ]:
#30.	Find the number of unique airlines.
a["airline"].nunique()

6

In [ ]:
#31.	Display the list of unique source cities.
a["source_city"].unique()

array(['Delhi', 'Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai'],
      dtype=object)

In [ ]:
#32.	Display the list of unique destination cities
a["destination_city"].unique()

array(['Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai', 'Delhi'],
      dtype=object)

In [ ]:
#33.	Count flights for each airline
a["airline"].value_counts()

airline
Vistara      106656
Air_India     67465
Indigo        36105
GO_FIRST      19368
AirAsia       13402
SpiceJet       7530
Name: count, dtype: int64

In [ ]:
#34.	Find the average ticket price.
a["price"].mean()

np.float64(20859.455409817743)

In [ ]:
#35.	Find the maximum ticket price.
a["price"].max()

123071

In [ ]:
#36.	Find the minimum ticket price.
a["price"].min()

1105

In [ ]:
#37.	Find the average ticket price for each airline.

a.groupby("airline")["price"].mean()

airline
AirAsia       4090.437397
Air_India    23462.339613
GO_FIRST      5650.079667
Indigo        5324.947320
SpiceJet      6180.799203
Vistara      30377.097941
Name: price, dtype: float64

In [ ]:
#38.	Display the top 5 most expensive flights.

a.groupby("flight")["price"].nlargest(5)

flight
0.00E+00  97174       8832
          100735      7220
          97470       6092
          98232       5178
          98608       5178
                     ...
UK-996    230092    114523
          241548    111964
          241599    111964
          230088    105764
          230089    105764
Name: price, Length: 7509, dtype: int64

In [ ]:
#39.	Find the number of flights from each source city.
a.groupby("source_city")["flight"].count()

source_city
Bangalore    43400
Chennai      32321
Delhi        51252
Hyderabad    33995
Kolkata      38765
Mumbai       50793
Name: flight, dtype: int64

In [ ]:
#40.	Find the number of flights to each destination city
a.groupby("destination_city")["flight"].count()

destination_city
Bangalore    42789
Chennai      33733
Delhi        47760
Hyderabad    35641
Kolkata      41396
Mumbai       49207
Name: flight, dtype: int64

In [ ]:
#41.	Identify the source city with the most flights.
a.groupby("source_city")["flight"].max()

source_city
Bangalore    UK-897
Chennai      UK-838
Delhi        UK-995
Hyderabad    UK-898
Kolkata      UK-778
Mumbai       UK-996
Name: flight, dtype: object

In [ ]:
#42.	Find the average ticket price for each source city.
a.groupby("source_city")["price"].mean()

source_city
Bangalore    21357.327535
Chennai      21931.586956
Delhi        18930.201904
Hyderabad    20208.695749
Kolkata      21785.402528
Mumbai       21427.374638
Name: price, dtype: float64

In [ ]:
#43.	Count flights based on number of stops.
a.groupby("flight")["stops"].count()

flight
0.00E+00       42
6.00E-102      33
6.00E-105       5
6.00E-113      37
6.00E-121      19
             ...
UK-988       1133
UK-993        738
UK-994       1064
UK-995        836
UK-996       1070
Name: stops, Length: 1555, dtype: int64

In [ ]:
#44.	Find the average price based on flight class.
a.groupby("class")["price"].mean()

class
Business    52533.982832
Economy      6571.986777
Name: price, dtype: float64

In [ ]:
#45.	Find the airline with the highest average passenger rating.
a.groupby("airline")["Passenger_Rating"].mean()

airline
AirAsia      3.127145
Air_India    3.130423
GO_FIRST     3.140438
Indigo       3.122365
SpiceJet     3.128685
Vistara      3.126360
Name: Passenger_Rating, dtype: float64

In [ ]:
a.columns

Index(['index', 'airline', 'flight', 'source_city', 'departure_time', 'stops',
       'arrival_time', 'destination_city', 'class', 'duration', 'days_left',
       'price', 'Passenger_Rating', 'Ticket_Type', 'Meal_Option', 'Baggage_kg',
       'Checkin_Status', 'Airport_Terminal', 'Delay_Minutes', 'Customer_ID'],
      dtype='object')

In [ ]:
#46.	Count flights based on departure time.
a.groupby("flight")["departure_time"].count()

flight
0.00E+00       42
6.00E-102      33
6.00E-105       5
6.00E-113      37
6.00E-121      19
             ...
UK-988       1133
UK-993        738
UK-994       1064
UK-995        836
UK-996       1070
Name: departure_time, Length: 1555, dtype: int64

In [ ]:
#47.	Find the average delay minutes of flights.
a.groupby("flight")["Delay_Minutes"].count()

flight
0.00E+00       42
6.00E-102      33
6.00E-105       5
6.00E-113      37
6.00E-121      19
             ...
UK-988       1133
UK-993        738
UK-994       1064
UK-995        836
UK-996       1070
Name: Delay_Minutes, Length: 1555, dtype: int64

In [ ]:
#48.	Display flights delayed more than 30 minutes.
a["Delay_Minutes"].unique()

array([30., 10.,  0.,  5., 15., 60.])

In [ ]:
a["Delay_Minutes"]=a["Delay_Minutes"].astype(float)

In [ ]:
a.loc[a["Delay_Minutes"]>30,["flight"]]

         flight
12      6E-5001
28      SG-8169
33       UK-817
34       UK-819
37       AI-453
...         ...
300100   UK-838
300106   UK-834
300136   UK-834
300142   AI-539
300145   AI-430

[31318 rows x 1 columns]

In [ ]:
a.to_csv("final_Cleaned_airline_database.csv",index=False)

In [ ]:
#50.	Display the final shape of the cleaned dataset.
a.shape

(250526, 20)

In [ ]:
a.isnull().sum()

index               0
airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
Passenger_Rating    0
Ticket_Type         0
Meal_Option         0
Baggage_kg          0
Checkin_Status      0
Airport_Terminal    0
Delay_Minutes       0
Customer_ID         0
dtype: int64

In [ ]:
a["Customer_ID"].fillna("unknown",inplace=True)

/tmp/ipykernel_4999/922340723.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  a["Customer_ID"].fillna("unknown",inplace=True)

In [ ]:
a["Delay_Minutes"].unique()

array([30., 10.,  0.,  5., 15., 60.])

In [ ]:
a["Airport_Terminal"].replace({"terminal-2":"T2","Terminal 1":"T1"},inplace=True)

In [ ]:
a["Airport_Terminal"].fillna("unknown",inplace=True)

In [ ]:
a["Checkin_Status"].fillna("unknown",inplace=True)

In [ ]:
a["Meal_Option"].replace({"veg ":"Veg","NONE":"unknown"},inplace=True)

In [ ]:
a["Meal_Option"].fillna("unkown",inplace=True)

In [ ]:
a["Ticket_Type"].replace({" refundable ":"Refundable","NON REFUNDABLE":"Non Refundable"},inplace=True)

In [ ]:
a["Passenger_Rating"].fillna(a["Passenger_Rating"].mean(),inplace=True)

/tmp/ipykernel_4999/2647121734.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  a["Passenger_Rating"].fillna(a["Passenger_Rating"].mean(),inplace=True)

In [ ]:
a["Ticket_Type"].fillna("unknown",inplace=True)

In [ ]:
a["Baggage_kg"].unique()

array([30, nan, '25', '15', '20'], dtype=object)

In [ ]:
a["Baggage_kg"].replace({"30kg":30,"25":25,"15":15,"20":20},inplace=True)

In [ ]:
import numpy as np

In [ ]:
a["Baggage_kg"].replace("unknown",np.nan,inplace=True)

In [ ]:
a["Baggage_kg"].fillna(a["Baggage_kg"].mean(),inplace=True)